services:
  ishaprawy-dashboard:
    build:
     context: .
     dockerfile: Dockerfile.dev
    container_name: ishaprawy-dashboard
    env_file: .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000